import sys
from pathlib import Path

try:
    from core.config import AegisConfig
    from utils.preprocessing import Preprocessor
    from core.tools.registry import get_registry
except ImportError as e:
    print(f"\n❌ Error importing Aegis-X modules: {e}")
    print("Please make sure you have activated your virtual environment and installed dependencies:")
    print("  .\\.venv\\Scripts\\activate")
    print("  pip install -r requirements.txt\n")
    sys.exit(1)

def main(media_path: str):
    path = Path(media_path)
    if not path.exists():
        print(f"Error: File '{path}' not found.")
        sys.exit(1)

    print(f"============================================================")
    print(f"🛡️  Aegis-X Deepfake Detection Test Execution")
    print(f"============================================================")
    print(f"Analyzing Target: {path.absolute()}\n")

    # Initialize Config & Preprocessor
    config = AegisConfig()
    preprocessor = Preprocessor(config)

    print("[1/3] Preprocessing media (Face Detection & Alignment)...")
    prep_result = preprocessor.process_media(path)

    if not prep_result.has_face:
        print("❌ No faces detected in the media.")
        sys.exit(0)

    print(f"✅ Detected {len(prep_result.tracked_faces)} face(s).")
    
    input_data = {
        "tracked_faces": prep_result.tracked_faces,
        "frames_30fps": prep_result.frames_30fps,
        "original_media_type": prep_result.original_media_type,
    }

    print("\n[2/3] Executing CPU Forensic Tools...")
    print("      (Skipping GPU tools to ensure basic execution runs globally)")
    registry = get_registry()
    
    # We test safe CPU tools that don't depend on missing PyTorch/Transformers configuration
    cpu_tools = ["check_c2pa", "run_dct", "run_geometry", "run_illumination"]
    
    results = {}
    
    for tool_name in cpu_tools:
        print(f"\n  -> Running {tool_name}...")
        res = registry.execute_tool(tool_name, input_data)
        results[tool_name] = res
        status = "✅ Success" if res.success else f"❌ Failed ({res.error_msg})"
        
        print(f"     Status:     {status}")
        if res.success:
            print(f"     Score:      {res.score:.3f}")
            print(f"     Confidence: {res.confidence:.3f}")
            print(f"     Evidence:   {res.evidence_summary}")

    print("\n[3/3] Final Summary:")
    print("============================================================")
    scores = [r.score for r in results.values() if r.success and r.tool_name != "check_c2pa"]
    if scores:
        avg_score = sum(scores) / len(scores)
        verdict = "⚠️ FAKE" if avg_score > 0.50 else "✅ REAL"
        print(f"Aggregated Basic Score:  {avg_score:.3f}")
        print(f"Preliminary CPU Verdict: {verdict}")
    else:
        print("No valid scores generated by CPU tools.")
        
    print("============================================================")
    print("Note: Run the full ensemble (including GPU models like SigLIP/SBI) for a definitive result.")

if __name__ == "__main__":
    target = "test.jpg"
    if len(sys.argv) > 1:
        target = sys.argv[1]
    
    main(target)
